First go at standalone

diff --git a/CrashPlanRemote b/CrashPlanRemote
--- a/CrashPlanRemote
+++ b/CrashPlanRemote
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -x
 
 # CrashPlanRemote
 # Andy Sayler
@@ -28,26 +29,17 @@ CPTYPE=$1
 REMOTEHOST=$2
 
 #TODO: Make these configurable
-if [[ ${CPTYPE} == "pro" ]]
-then
-    CRASHPLAN_INSTALL="${HOME}/crashplanpro/crashplan/"
-elif [[ ${CPTYPE} == "home" ]]
-then
-    CRASHPLAN_INSTALL="${HOME}/crashplan/crashplan/"
-else
-    display_usage
-    exit 1
-fi
-
+CRASHPLAN_INSTALL="/tmp/crashplan/"
 CRASHPLAN_DESKTOP="${CRASHPLAN_INSTALL}/bin/CrashPlanDesktop"
 
-if [[ ! -d "${CRASHPLAN_INSTALL}" ]]
-then
-    echo "Could not find CrashPlanPro install at ${CRASHPLAN_INSTALL}"
-    echo "Have you installed CrashPlanPro to that location?"
-    exit 1
-fi
+# if [[ ! -d "${CRASHPLAN_INSTALL}" ]]
+# then
+#     echo "Could not find CrashPlanPro install at ${CRASHPLAN_INSTALL}"
+#     echo "Have you installed CrashPlanPro to that location?"
+#     exit 1
+# fi
 
+CRASHPLAN_DIR_REMOTE="/usr/local/crashplan"
 INFO_DIR_LOCAL="${HOME}/.crashplan"
 INFO_DIR_REMOTE="/var/lib/crashplan"
 INFO_FILE=".ui_info"
@@ -59,6 +51,37 @@ INFO_PATH_OLD="${INFO_DIR_LOCAL}/${INFO_FILE_OLD}"
 
 PORT_ORIG="4243"
 PORT_NEW="4200"
+
+# Get Remote Install
+if [[ -d "${CRASHPLAN_INSTALL}" ]]
+then
+    rm -rf "${CRASHPLAN_INSTALL}"
+fi
+mkdir "${CRASHPLAN_INSTALL}"
+
+rsync -avz ${REMOTEHOST}:"${CRASHPLAN_DIR_REMOTE}/bin" "${CRASHPLAN_INSTALL}/"
+rsync -avz ${REMOTEHOST}:"${CRASHPLAN_DIR_REMOTE}/jre" "${CRASHPLAN_INSTALL}/"
+rsync -avz ${REMOTEHOST}:"${CRASHPLAN_DIR_REMOTE}/lang" "${CRASHPLAN_INSTALL}/"
+rsync -avz ${REMOTEHOST}:"${CRASHPLAN_DIR_REMOTE}/lib" "${CRASHPLAN_INSTALL}/"
+rsync -avz ${REMOTEHOST}:"${CRASHPLAN_DIR_REMOTE}/skin" "${CRASHPLAN_INSTALL}/"
+rsync -avz ${REMOTEHOST}:"${CRASHPLAN_DIR_REMOTE}/*.so" "${CRASHPLAN_INSTALL}/"
+
+mkdir "${CRASHPLAN_INSTALL}/log"
+touch "${CRASHPLAN_INSTALL}/log/ui_error.log"
+touch "${CRASHPLAN_INSTALL}/log/ui_output.log"
+mkdir "${CRASHPLAN_INSTALL}/conf"
+touch "${CRASHPLAN_INSTALL}/install.vars"
+
+echo "TARGETDIR=${CRASHPLAN_INSTALL}" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "BINSDIR=" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "MANIFESTDIR=${CRASHPLAN_INSTALL}/manifest" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "INITIR=" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "RUNLVLDIR=" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "INSTALLDATE=" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "APP_BASENAME=CrashPlan" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "DIR_BASENAME=crashplan" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "DOWNLOAD_HOST=download.crashplan.com" >> "${CRASHPLAN_INSTALL}/install.vars"
+echo "JAVACOMMON=${CRASHPLAN_INSTALL}/jre/bin/java" >> "${CRASHPLAN_INSTALL}/install.vars"
 
 # Setup
 if [[ ! -d "${INFO_DIR_LOCAL}" ]]
